### ISSUE TITLE
Whitelabel Error Page in Awwvision

### ISSUE THREAD

**Issue by jeremykeen** [cf-platform-eng/gcp-pcf-quickstart#2]
Getting error below when click "update with latest images" in the Awwvision app.  
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Jan 23 15:25:45 UTC 2018
There was an unexpected error (type=Internal Server Error, status=500).
No message available

Logs from 'cf logs awwvision':

Retrieving logs for app awwvision in org dev / space dev as admin...

   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT 2018-01-23 15:50:51.094 ERROR 19 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
   2018-01-23T10:50:51.11-0500 [RTR/0] OUT awwvision-<removed>.apps.pcf.<removed> - [2018-01-23T15:50:50.787+0000] "GET /reddit HTTP/1.1" 500 0 318 "http://awwvision-<removed>/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" "<removed>:53231" "<removedIP>:61038" x_forwarded_for:"<removedIP>, <removed>" x_forwarded_proto:"http" vcap_request_id:"ec6fa03c-c250-4ac6-790b-3c36ff10ad0a" response_time:0.325393009 app_id:"07d1a2f6-ccec-45e0-8417-ef29dff18bdd" app_index:"0" x_b3_traceid:"502619426b2ed8dd" x_b3_spanid:"502619426b2ed8dd" x_b3_parentspanid:"-"
   2018-01-23T10:50:51.11-0500 [RTR/0] OUT
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT java.lang.NullPointerException: null
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at com.google.cloud.servicebroker.awwvision.RedditScraper.storeAndLabel(RedditScraper.java:71) ~[classes/:na]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at com.google.cloud.servicebroker.awwvision.RedditScraper.getRedditUrls(RedditScraper.java:64) ~[classes/:na]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105) ~[spring-boot-actuator-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87) ~[spring-web-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:107) ~[spring-boot-actuator-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:77) ~[client_certificate_mapper-1.3.0_RELEASE.jar!/:1.3.0.RELEASE]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.4.jar!/:8.5.4]
   2018-01-23T10:50:51.09-0500 [APP/PROC/WEB/0] OUT     at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]

**Comment by johnsonj** [comment]
Looks like this [post](https://www.reddit.com/r/aww/comments/7p8195/bestof_raww_2017_voting_thread/) is breaking it because the API doesn't provide a 'preview' field for self posts:
<details/>
  <summary>Text only post</summary>
```
data: {
domain: "self.aww",
approved_at_utc: null,
mod_reason_by: null,
banned_by: null,
num_reports: null,
subreddit_id: "t5_2qh1o",
thumbnail_width: null,
subreddit: "aww",
selftext_html: "&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;We get 20 creddits to hand out this year. We&amp;#39;re going to do 10 categories, with 1st and 2nd place each getting 1 creddit. &lt;/p&gt; &lt;p&gt;The categories are:&lt;/p&gt; &lt;ul&gt; &lt;li&gt;&lt;p&gt;Overall cutest post&lt;/p&gt;&lt;/li&gt; &lt;li&gt;&lt;p&gt;Cutest cat/kitten&lt;/p&gt;&lt;/li&gt; &lt;li&gt;&lt;p&gt;Cutest dog/puppy&lt;/p&gt;&lt;/li&gt; &lt;li&gt;&lt;p&gt;Cutest human&lt;/p&gt;&lt;/li&gt; &lt;li&gt;&lt;p&gt;Cutest other (anything not a cat/dog/human)&lt;/p&gt;&lt;/li&gt; &lt;li&gt;&lt;p&gt;Cutest multiple species (cat+dog/cat+human/dog+human/dog+cat+human/etc)&lt;/p&gt;&lt;/li&gt; &lt;li&gt;&lt;p&gt;Cutest underappreciated submission (&amp;lt;10,000 upvotes on the post)&lt;/p&gt;&lt;/li&gt; &lt;li&gt;&lt;p&gt;Best comment&lt;/p&gt;&lt;/li&gt; &lt;li&gt;&lt;p&gt;Silliest post&lt;/p&gt;&lt;/li&gt; &lt;li&gt;&lt;p&gt;Cutest fail&lt;/p&gt;&lt;/li&gt; &lt;/ul&gt; &lt;p&gt;This was the nomination thread:&lt;/p&gt; &lt;p&gt;&lt;a href="https://www.reddit.com/r/aww/comments/7jjnz5/bestof_raww_2017_nominations_thread/"&gt;https://www.reddit.com/r/aww/comments/7jjnz5/bestof_raww_2017_nominations_thread/&lt;/a&gt;&lt;/p&gt; &lt;p&gt;The nominations are posted below. Vote for your favorite nomination in each category, and feel free to vote multiple times.&lt;/p&gt; &lt;p&gt;We&amp;#39;ll post the winners in like a week or something when we get around to it. I totally promise not to just hoard all the gold for myself.&lt;/p&gt; &lt;p&gt;&lt;strong&gt;edit&lt;/strong&gt; Note: this thread is in contest mode. You have to expand the comments underneath each category to see the nominations.&lt;/p&gt; &lt;/div&gt;&lt;!-- SC_ON --&gt;",
selftext: "We get 20 creddits to hand out this year. We're going to do 10 categories, with 1st and 2nd place each getting 1 creddit. The categories are: * Overall cutest post * Cutest cat/kitten * Cutest dog/puppy * Cutest human * Cutest other (anything not a cat/dog/human) * Cutest multiple species (cat+dog/cat+human/dog+human/dog+cat+human/etc) * Cutest underappreciated submission (&lt;10,000 upvotes on the post) * Best comment * Silliest post * Cutest fail This was the nomination thread: https://www.reddit.com/r/aww/comments/7jjnz5/bestof_raww_2017_nominations_thread/ The nominations are posted below. Vote for your favorite nomination in each category, and feel free to vote multiple times. We'll post the winners in like a week or something when we get around to it. I totally promise not to just hoard all the gold for myself. **edit** Note: this thread is in contest mode. You have to expand the comments underneath each category to see the nominations.",
likes: null,
suggested_sort: null,
user_reports: [ ],
secure_media: null,
is_reddit_media_domain: false,
link_flair_text: null,
id: "7p8195",
banned_at_utc: null,
mod_reason_title: null,
view_count: null,
archived: false,
clicked: false,
media_embed: { },
report_reasons: null,
author: "N8theGr8",
num_crossposts: 0,
saved: false,
mod_reports: [ ],
can_mod_post: false,
is_crosspostable: false,
pinned: false,
score: 196,
approved_by: null,
over_18: false,
hidden: false,
thumbnail: "self",
edited: 1515527748,
link_flair_css_class: null,
author_flair_css_class: null,
contest_mode: true,
gilded: 0,
downs: 0,
brand_safe: true,
secure_media_embed: { },
removal_reason: null,
author_flair_text: null,
stickied: true,
can_gild: false,
thumbnail_height: null,
parent_whitelist_status: "all_ads",
name: "t3_7p8195",
spoiler: false,
permalink: "/r/aww/comments/7p8195/bestof_raww_2017_voting_thread/",
subreddit_type: "public",
locked: true,
hide_score: false,
created: 1515542730,
url: "https://www.reddit.com/r/aww/comments/7p8195/bestof_raww_2017_voting_thread/",
whitelist_status: "all_ads",
quarantine: false,
title: "Bestof /r/Aww 2017 voting thread!",
created_utc: 1515513930,
subreddit_name_prefixed: "r/aww",
ups: 196,
media: null,
num_comments: 65,
is_self: true,
visited: false,
mod_note: null,
is_video: false,
distinguished: null
}
```
</details>

<details/>
<summary>typical image response</summary>

```
data: {
domain: "i.redd.it",
approved_at_utc: null,
mod_reason_by: null,
banned_by: null,
num_reports: null,
subreddit_id: "t5_2qh1o",
thumbnail_width: 140,
subreddit: "aww",
selftext_html: null,
selftext: "",
likes: null,
suggested_sort: null,
user_reports: [ ],
secure_media: null,
is_reddit_media_domain: true,
link_flair_text: null,
id: "7sdp8r",
banned_at_utc: null,
mod_reason_title: null,
view_count: null,
archived: false,
clicked: false,
media_embed: { },
report_reasons: null,
author: "DopeMcClane",
num_crossposts: 0,
saved: false,
mod_reports: [ ],
can_mod_post: false,
is_crosspostable: false,
pinned: false,
score: 41115,
approved_by: null,
over_18: false,
hidden: false,
preview: {
images: [
{
source: {
url: "https://i.redditmedia.com/524ajSIBpt3Ky-qqdPRBdzLyp5qb2EnEuRQ-wnlIOcc.jpg?s=a216d8cecb956b4d165f6b4f85ee15c9",
width: 1070,
height: 1070
},
resolutions: [
{
url: "https://i.redditmedia.com/524ajSIBpt3Ky-qqdPRBdzLyp5qb2EnEuRQ-wnlIOcc.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=108&amp;s=d669c9e3b95da2b6ef2e35cb1f4db910",
width: 108,
height: 108
},
{
url: "https://i.redditmedia.com/524ajSIBpt3Ky-qqdPRBdzLyp5qb2EnEuRQ-wnlIOcc.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=216&amp;s=12cfc8dc2e92f1d2a1a00b380466dd3a",
width: 216,
height: 216
},
{
url: "https://i.redditmedia.com/524ajSIBpt3Ky-qqdPRBdzLyp5qb2EnEuRQ-wnlIOcc.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=90aa428cf8071c019a63fd4616191384",
width: 320,
height: 320
},
{
url: "https://i.redditmedia.com/524ajSIBpt3Ky-qqdPRBdzLyp5qb2EnEuRQ-wnlIOcc.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=640&amp;s=14c8c8bcbe2c187a64efdce2630a8132",
width: 640,
height: 640
},
{
url: "https://i.redditmedia.com/524ajSIBpt3Ky-qqdPRBdzLyp5qb2EnEuRQ-wnlIOcc.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=960&amp;s=828a57d0557394b87064c611f911d646",
width: 960,
height: 960
}
],
variants: { },
id: "3zcjoFjVFo0-TUyKluQ3dKZY1O4gSA1odd2Aoi8r9YA"
}
],
enabled: true
},
thumbnail: "https://b.thumbs.redditmedia.com/fpiGRLcnyDxs_LWuEGjJY_vdwZqMCnPb4dvn3vJIogs.jpg",
edited: false,
link_flair_css_class: null,
author_flair_css_class: null,
contest_mode: false,
gilded: 0,
downs: 0,
brand_safe: true,
secure_media_embed: { },
removal_reason: null,
post_hint: "image",
author_flair_text: null,
stickied: false,
can_gild: false,
thumbnail_height: 140,
parent_whitelist_status: "all_ads",
name: "t3_7sdp8r",
spoiler: false,
permalink: "/r/aww/comments/7sdp8r/his_name_is_buddha/",
subreddit_type: "public",
locked: false,
hide_score: false,
created: 1516734643,
url: "https://i.redd.it/vdq9iu2nvsb01.jpg",
whitelist_status: "all_ads",
quarantine: false,
title: "His name is Buddha!",
created_utc: 1516705843,
subreddit_name_prefixed: "r/aww",
ups: 41115,
media: null,
num_comments: 710,
is_self: false,
visited: false,
mod_note: null,
is_video: false,
distinguished: null
}
```
</details>

**Comment by johnsonj** [comment]
thanks @jeremykeen!

**Comment by jeremykeen** [comment]
Working now @johnsonj , thanks!
